# Generated by Django 4.2.6 on 2024-01-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingresult',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio'),
        ),
        migrations.AddField(
            model_name='reportingresult',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio'),
        ),
        migrations.AddField(
            model_name='reportingresult',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio'),
        ),
        migrations.AddField(
            model_name='reportingresult',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio'),
        ),
    ]
