# Generated by Django 4.2.6 on 2024-01-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_reportingresult_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportingresult',
            options={'ordering': ['date'], 'verbose_name': 'Reporting Result', 'verbose_name_plural': 'Reporting Results'},
        ),
    ]
